name: Deploy Monitoring - dev

on:
  workflow_dispatch:
  push:
    branches:
      - feature/sv-vp-463-separate-infra-mon  # TEMP: remove before merging to main

permissions: {}
concurrency:
  group: backend-monitoring-dev
  cancel-in-progress: false

jobs:
  deploy-monitoring-dev:
    name: Deploy Monitoring Helm Chart - dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: dev
    steps:
      - name: Authenticate to the cluster
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
        run: |
          echo "${{ secrets.KUBE_CERT }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${{ secrets.KUBE_NAMESPACE }}
          kubectl config use-context ${KUBE_CLUSTER}

      - name: Clone Helm chart repo
        run: |
          git clone https://github.com/ministryofjustice/track-my-case-cloud-platform.git
          git -C track-my-case-cloud-platform checkout feature/sv-vp-463-separate-infra-mon

      - name: Adopt existing monitoring resources into new Helm release
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
        run: |
          NEW_RELEASE="stg-track-my-case-monitoring"
          PATCH='{"metadata":{"annotations":{"meta.helm.sh/release-name":"'"$NEW_RELEASE"'","meta.helm.sh/release-namespace":"'"$KUBE_NAMESPACE"'"}}}'

          for resource in \
            "prometheusrule/alerting-rules-$KUBE_NAMESPACE" \
            "configmap/${NEW_RELEASE}-dashboard" ; do
            if kubectl get $resource -n $KUBE_NAMESPACE >/dev/null 2>&1; then
              echo "Patching $resource..."
              kubectl patch $resource -n $KUBE_NAMESPACE --type=merge -p "$PATCH"
            else
              echo "$resource not found — skipping"
            fi
          done

      - name: Deploy Monitoring Helm chart
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
        run: |
          helm upgrade --install stg-track-my-case-monitoring \
            ./track-my-case-cloud-platform/charts/stg-track-my-case-monitoring \
            -f ./track-my-case-cloud-platform/charts/stg-track-my-case-monitoring/values-dev.yaml \
            --namespace $KUBE_NAMESPACE --wait

            