name: Publish pact contracts to pact broker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish-pacts:
    runs-on: ubuntu-latest

    env:
      PACT_BROKER_URL: https://hmcts-dts.pactflow.io
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      GIT_COMMIT: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref_name }}
      PACT_ENV: dev/pactTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permissions for scripts
        run: chmod +x ./publish-pacts.sh

      - name: Install Pact CLI
        run: npm install -g @pact-foundation/pact-cli

      - name: Run pact publish script
        run: ./publish-pacts.sh
